// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhWhiAoLLBMbiKnPTVgIelfm_GpG5QN8c',
    appId: '1:941243855146:web:f6a772db5452b782b4ae53',
    messagingSenderId: '941243855146',
    projectId: 'happy-47972',
    authDomain: 'happy-47972.firebaseapp.com',
    storageBucket: 'happy-47972.appspot.com',
    measurementId: 'G-JK4YXR9SMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbcmfyo2-UTTezyj0am38QQN26LuUAJK0',
    appId: '1:941243855146:android:93b30494332982f6b4ae53',
    messagingSenderId: '941243855146',
    projectId: 'happy-47972',
    storageBucket: 'happy-47972.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfEjQDGAxLA-Ahi2I06YHy079CHKDpgZ0',
    appId: '1:941243855146:ios:9b7506301821bbb1b4ae53',
    messagingSenderId: '941243855146',
    projectId: 'happy-47972',
    storageBucket: 'happy-47972.appspot.com',
    iosClientId: '941243855146-qgoag5ta0137hiu0ubrvgjbragqmgsjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfEjQDGAxLA-Ahi2I06YHy079CHKDpgZ0',
    appId: '1:941243855146:ios:9b7506301821bbb1b4ae53',
    messagingSenderId: '941243855146',
    projectId: 'happy-47972',
    storageBucket: 'happy-47972.appspot.com',
    iosClientId: '941243855146-qgoag5ta0137hiu0ubrvgjbragqmgsjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
